language: python
python:
  #- "2.7"
  #- "3.2"
  #- "3.3"
  - "3.4"
  - "3.6"
  #- "3.7"
  # PyPy versions
  #- "pypy"  # PyPy2 2.5.0
  #- "pypy3" # Pypy3 2.4.0
  #- "pypy-5.3.1"
# command to install dependencies
install:
  - pip install pandas
  - pip install .
  - pip install matplotlib
  - pip install numpy
  - pip install seaborn
  #- pip install -r requirements.txt
# command to run tests
script: pytest ./shapes/tests/test_shapes.py